DEFUN("gl-draw-arrays-instanced", Fgl_draw_arrays_instanced, 4, 4, "(gl-draw-arrays-instanced mode first count instancecount)\nglDrawArraysInstanced.", NULL);
DEFUN("gl-tex-buffer", Fgl_tex_buffer, 3, 3, "(gl-tex-buffer target internalformat buffer)\nglTexBuffer.", NULL);
DEFUN("gl-primitive-restart-index", Fgl_primitive_restart_index, 1, 1, "(gl-primitive-restart-index index)\nglPrimitiveRestartIndex.", NULL);
DEFUN("gl-uniform-block-binding", Fgl_uniform_block_binding, 3, 3, "(gl-uniform-block-binding program uniformBlockIndex uniformBlockBinding)\nglUniformBlockBinding.", NULL);
DEFUN("gl-bind-buffer-base", Fgl_bind_buffer_base, 3, 3, "(gl-bind-buffer-base target index buffer)\nglBindBufferBase.", NULL);
