DEFUN("gl-uniform-matrix2x3fv", Fgl_uniform_matrix2x3fv, 4, 4, "(gl-uniform-matrix2x3fv location count transpose value)\nglUniformMatrix2x3fv.", NULL);
DEFUN("gl-uniform-matrix3x2fv", Fgl_uniform_matrix3x2fv, 4, 4, "(gl-uniform-matrix3x2fv location count transpose value)\nglUniformMatrix3x2fv.", NULL);
DEFUN("gl-uniform-matrix2x4fv", Fgl_uniform_matrix2x4fv, 4, 4, "(gl-uniform-matrix2x4fv location count transpose value)\nglUniformMatrix2x4fv.", NULL);
DEFUN("gl-uniform-matrix4x2fv", Fgl_uniform_matrix4x2fv, 4, 4, "(gl-uniform-matrix4x2fv location count transpose value)\nglUniformMatrix4x2fv.", NULL);
DEFUN("gl-uniform-matrix3x4fv", Fgl_uniform_matrix3x4fv, 4, 4, "(gl-uniform-matrix3x4fv location count transpose value)\nglUniformMatrix3x4fv.", NULL);
DEFUN("gl-uniform-matrix4x3fv", Fgl_uniform_matrix4x3fv, 4, 4, "(gl-uniform-matrix4x3fv location count transpose value)\nglUniformMatrix4x3fv.", NULL);
